-- 用户反馈（留言）表：登录用户提交，仅管理员可见
CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  username VARCHAR(64) NOT NULL,
  category VARCHAR(32) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  page_path VARCHAR(512),
  status VARCHAR(16) NOT NULL,
  handled_at TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_feedback_created_at ON feedback (created_at DESC);
CREATE INDEX idx_feedback_status_created_at ON feedback (status, created_at DESC);

COMMENT ON TABLE feedback IS '用户反馈（留言）表';
COMMENT ON COLUMN feedback.user_id IS '提交用户 ID，不做外键，与现有业务表一致';
COMMENT ON COLUMN feedback.username IS '提交时用户名快照，管理端列表免联表';
COMMENT ON COLUMN feedback.category IS '反馈分类：BUG/SUGGESTION/EXPERIENCE/OTHER';
COMMENT ON COLUMN feedback.content IS '反馈正文，5-1000 字';
COMMENT ON COLUMN feedback.page_path IS '提交时所在页面路径，最长 512';
COMMENT ON COLUMN feedback.status IS '处理状态：PENDING/PROCESSED';
COMMENT ON COLUMN feedback.handled_at IS '标记为已处理的时间，回退待处理时置空';
