-- 用户表：登录账号 + 密码哈希，为后续业务数据按用户隔离提供主体
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT uk_users_username UNIQUE (username)
);

COMMENT ON TABLE users IS '用户账号表';
COMMENT ON COLUMN users.username IS '登录账号，唯一，注册校验 3-32 位字母/数字/下划线';
COMMENT ON COLUMN users.password_hash IS 'BCrypt 哈希后的密码，禁止存储明文';
